language: objective-c
osx_image: xcode8
branches:
  only:
    - dev
script:
- if [ $MODE == 'Tests' ]; then xcodebuild -workspace metalic.xcworkspace -scheme metalic clean build test; fi
- if [ $MODE == 'Build' ]; then xcodebuild -workspace metalic.xcworkspace -scheme metalic clean build; fi
notifications:
  email:
    on_success: never
    on_failure: never
env:
  matrix:
  - MODE=Tests
  - MODE=Build
